version: '3.8'

services:
  router:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TOR_PROXY_URL=socks5://tor:9050
    ports:
      - 8000:8000

  tor:
    image: ghcr.io/hundehausen/tor-hidden-service:latest
    volumes:
      - tor-data:/var/lib/tor
    environment:
      # Format: HS_<NAME>=<TARGET_HOST>:<TARGET_PORT>:<VIRTUAL_PORT>
      - HS_ROUTER=router:8000:80
    depends_on:
      - router
  
  relay:
    image: dockurr/strfry:latest
    restart: unless-stopped
    ports:
      - "8088:8080"  # host:container
    volumes:
      - ./.relay/data:/app/strfry-db
      - ./.relay/strfry.conf:/app/strfry.conf:ro
    command: ["./strfry", "relay"]

volumes:
  tor-data:
